version: "3"

services:
  postgres:
    image: "postgres:9.5"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"

  app:
    depends_on:
      - "postgres"
    build: .
    command: bash start.sh
    environment:
      NODE_ENV: production
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/fileserver

volumes:
  ? postgres
