version: "3"

services:
  redis:
    image: "redis:5-alpine"

  postgres:
    env_file:
      - ./.env
    image: "postgres:11.2-alpine"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASS}"

    restart: always

  app:
    env_file:
      - ./.env
    depends_on:
      - "postgres"
      - "redis"
    build: .
    command: bash start.sh
    environment:
      NODE_ENV: production
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/usr/src/nuvem42
      - ./${MEDIA_ROOT}:${MEDIA_BIND}

    restart: always

volumes:
  postgres:
  app:
